---
- hosts: test
  gather_facts: yes
  tasks:
    - name: Install repo
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
        state: present
    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    - name: Install MySQL-server
      yum:
        name: mysql-server
        state: latest
    - name: start MySQL server daemon
      service:
        name: mysqld
        state: started

